sudo: required
language: node_js

node_js:
  - 7

script: npm run build

install:
  - npm i -g npm@latest
  - npm install

before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

notifications:
  email:
    on_failure: change

# after_success: 'npm run coveralls'

cache:
  directories:
    - node_modules
