sudo: required
language: node_js

node_js:
  - 7

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: yarn run build

notifications:
  email:
    on_failure: change

after_success: 'yarn run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
