sudo: required
language: node_js
node_js:
  - 6
  - 7

# required for microtime npm module
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script:
  # microtime needs to build binaries, so lets explicitly reinstall it (the cached version is always fubar)
  - yarn remove microtime
  - yarn add microtime
  - yarn run build

notifications:
  email:
    on_failure: change

after_success: 'yarn run coverage'

cache:
  yarn: true
  directories:
    - node_modules
